### ISSUE TITLE
v2 changelog?

### ISSUE THREAD

**Issue by raineorshine** [sindresorhus/find-up#10]
Is there a change log of breaking changes in v2? Thanks!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/find-up/compare/v1.1.2...v2.0.0

**Comment by sholladay** [comment]
- Require Node.js >= 4.
 - A weird way of using this module, supplying an absolute path as the `filename` argument, will not work anymore (at least on Windows). See https://github.com/sindresorhus/find-up/pull/7.

**Comment by raineorshine** [comment]
There's always studying the diff and hoping I see the breaking changes... :D

Thanks ;)
