### ISSUE TITLE
Inaccurate description

### ISSUE THREAD

**Issue by davej** [sindresorhus/find-up#15]
Description of the `find-up` package is:

> Find a **file** by walking up parent directories

However, it also finds directories. Please consider changing either the description or the functionality.

**Comment by sholladay** [comment]
Fair enough. Ideas?

 - > Find a file or directory by walking up parent directories
 - > Find a filepath by walking up parent directories
 - > Find a path by walking up parent directories


Or how about _"Find a file or directory by searching up through a directory and its parent directories"_. 😄

**Comment by davej** [comment]
I like these two:

* > Find a file or directory by walking up parent directories

or

* > Find a file/directory by walking up parent directories

**Comment by sindresorhus** [comment]
We could potentially have an option where you could specify whether you wanted a file or directory, but we would have to `fs.stat()` for every level then (so would have to be opt-in), and I've honestly never needed it. I always use it to find files with an extension.
