### ISSUE TITLE
Find-Up doesn't work in node_modules

### ISSUE THREAD

**Issue by schmidt-sebastian** [sindresorhus/find-up#25]
We are using find-up via pkg-up to find the package.json of our node module. However, if a user depends on our node module, our invocation of `find-up` starts traversing the package tree at the users code, and not inside of our module. We therefor end up using the users `package.json` and not our own. 

Node version: 8.11.3

**Comment by schmidt-sebastian** [comment]
Related: https://github.com/googleapis/nodejs-firestore/issues/278

**Comment by schmidt-sebastian** [comment]
I just noticed that I can pass `__dirname`, so I consider this fixed. Would be nice to have this documented more prominently.

**Comment by sholladay** [comment]
Yep, was just about to comment. 😄 

Tthe correct invocation is:

```js
const pkgPath = await pkgUp(__dirname);
```

That will use the directory that contains your module's code as the starting point for the search, rather than the current working directory of the shell.
