### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by hdorgeval** [sindresorhus/find-up#26]
Hello, I have this when I go to npm:

```text
Unexpected token u in JSON at position 0
id: wubwub-7-west:e13ef46f-fd86-47ce-82b3-00f54a224a2c
```
Does this mean I should not use your latest package?

**Comment by sindresorhus** [comment]
I don’t understand what you’re asking or how it’s related to this module. Your error looks totally unrelated.

**Comment by hdorgeval** [comment]
https://www.npmjs.com/package/find-up

**Comment by sindresorhus** [comment]
That doesn’t clear up anything.
