### ISSUE TITLE
The Typescript declaration file isn't installed even though it exists in the repository

### ISSUE THREAD

**Issue by ChristianIvicevic** [sindresorhus/find-up#39]
I just installed this package via yarn as usual running `yarn add find-up` but compared to you other packages the typings file isn't in the installed package under node_modules even though I can see it in the repository. Could you please look into this, whether your able to reproduce this issue?

**Comment by ChristianIvicevic** [comment]
Please disregard this issue, I am using yarn workspaces and `find-up` gets hoisted with a previously available version that I did not expect. This is most likely something I can only fix in the context of my project.

**Comment by ChristianIvicevic** [comment]
Oh I was wrong, it turns out, you just recently added the typings without publishing a new version to npm. In the meantime I have added the Github repo as a repository and I'd be glad if you can push a new update to npm with the typings included.

**Comment by sholladay** [comment]
Yep, we just need to do a release. We will be doing a major release (v4.0.0) and it's blocked by #33 because we plan to make `type: file` be the default behavior.

**Comment by ChristianIvicevic** [comment]
@sholladay @sindresorhus I have been running into issues since I have added the Github repository as a dependency to my current project instead of the npm package just to get the typings. Unfortunately my CI pipeline is having issues with Github dependencies and concurrent installations of the same dependency and thus fails.

Can you please publish a 3.0.1 version, with the typings included so I can directly install via npm?

**Comment by sindresorhus** [comment]
@ChristianIvicevic We will publish a new version when it's ready. You can just use `@types/find-up` with the current version of `find-up` on npm.
