### ISSUE TITLE
Option to find the containing directory

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/find-up#5]
Would you consider adding an option that reports the containing directory back to the user?

Assuming a directory structure like this:

```
/
└── Users
    └── sindresorhus
        ├── unicorn.png
        └── foo
            └── bar
                ├── baz
                └── example.js
```

It would be cool if there was a way to get the containing directory of the `unicorn.png` file without having to hack on the `filepath` string. For example, currently, I would have to do something like:

```js
// example.js
findUp('unicorn.png').then(filepath => {
    const dir = /*code to hack the filepath string*/;
    console.log(dir);
    //=> '/Users/sindresorhus/'
});
```
But if there was something like a `dir` method, I could get the containing directory back cleanly:

```js
// example.js
findUp.dir('unicorn.png').then(dirpath => {
    console.log(dirpath);
    //=> '/Users/sindresorhus/'
});
```
Or the `dir` method could return a `file` object with `path` and `dir`:

```js
// example.js
findUp.dir('unicorn.png').then(file => {
    console.log(file);
    /* '{
             path: '/Users/sindresorhus/unicorn.png',
             dir: `/Users/sindresorhus/`
          }
    */
});
```

**Comment by radiovisual** [comment]
I found this module called [find-dir](https://github.com/Arch-Mage/find-dir), but I prefer the API (and promise support) of find-up.

**Comment by sindresorhus** [comment]
Why not this?

```js
findUp('unicorn.png').then(filepath => {
	console.log(path.dirname(filepath));
	//=> '/Users/sindresorhus/'
});
```

**Comment by radiovisual** [comment]
True, that is a really clean way of getting the containing directory, and what I will be using for now.

In my mind, I suppose I just like how a `dir` (or similar) method in the API makes the intent very clear, being the difference between:

> "**I am searching for a file** (and then trying to find the containing directory of that file)"

**versus**

> "**I am searching for the containing directory of a file**"

**Comment by sindresorhus** [comment]
I think the intent of `findUp.dir()` would be unclear. I would assume it would find a directory upwards, not the parent directory of a file. `path.dirname()` is the solution here, not introducing more API surface.

**Comment by radiovisual** [comment]
I agree that `findUp.dir()` would read like it was finding a directory upwards, but the API usage of passing in a filename string like `findUp.dir('unicorns.png')` suddenly changes the semantics, and now (at least to me) it reads like "find the upwards directory containing the 'uniconrs.png'", but I agree, no additional API surface is needed when `path.dirname()` has clear intent. 

Thanks.
