### ISSUE TITLE
Usage of node:path is incompatible with declared engines

### ISSUE THREAD

**Issue by kachkaev** [sindresorhus/find-up#55]
👋 @sindresorhus!

I was [fiddling with prettier-vscode](https://github.com/prettier/prettier-vscode/pull/2201) and noticed an issue with [`find-up`’s import from `node:path`](https://github.com/sindresorhus/find-up/blob/ace3d10aadce889a78924954a2766af81eb315ff/index.js#L1). When running `yarn test`, the extension was crashing by saying that it could not resolve `node:path`.

According to [v6.0.0 CHANGELOG](https://github.com/sindresorhus/find-up/releases/tag/v6.0.0) and [package.json → engines](
https://github.com/sindresorhus/find-up/blob/ace3d10aadce889a78924954a2766af81eb315ff/package.json#L15-L17), `find-up` is expected to work on any Node version that supports ESM. However, looks like `node:path` import has a stricter constraint, more specifically [Node 14.18 and Node 16+](https://github.com/inspect-js/is-core-module/blob/6717f000d063ea57beb772bded36c2f056ac404c/core.json#L71).

**Comment by sindresorhus** [comment]
It is supported on Node.js 12 since 12.20:

https://github.com/sindresorhus/find-up/blob/ace3d10aadce889a78924954a2766af81eb315ff/package.json#L15-L17

**Comment by sindresorhus** [comment]
https://nodejs.org/en/blog/release/v12.20.0/

**Comment by kachkaev** [comment]
I must have been confused by the difference between `require('node:something)` and `import('node:something')` which work differently. Typing `require('node:something)` in Node v12.22.6 and Node v14.17.0 REPL produces `Uncaught Error: Cannot find module 'node:something'`, which is not the case for `import('node:something')` — this statements works. Node v14.18.0 is fixed, thanks to https://github.com/nodejs/node/pull/37246.

Prettier for VSCode is built by `webpack` and so [`import path from 'node:path'` in `find-up`]([mentions](https://github.com/sindresorhus/find-up/blob/ace3d10aadce889a78924954a2766af81eb315ff/index.js#L1)) gets replaced by `require` and breaks. This is not a problem of `find-up` though – seems that downstream webpack setups need to account for different version support for `require('node:something)` and `import('node:something')`.
