### ISSUE TITLE
Unhandled Rejection (TypeError): path.parse is not a function

### ISSUE THREAD

**Issue by bharathkv90** [sindresorhus/find-up#58]
```javascript
import find from 'find-up';
import dotenv from 'dotenv';

const envPath = find.sync('.env');
dotenv.config({ path: envPath });

console.log(process.env);
```

I am trying to find the path of the .env file that is present in the root workspace (using yarn for creating workspace). I am using the above code in a library. When the application runs I am getting 
```
Unhandled Rejection (TypeError): path.parse is not a function
```
Please help me fix this error.

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
