### ISSUE TITLE
Find up until file does NOT exist.

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/find-up#6]
I am making a developer tool to help manage our zillions of modules. For example, find all my modules that have pinned dependencies so I can see if that is no longer necessary.

One thing it needs to be able to do is figure out where the modules live. If my working directory is `~/Code/my-module` it needs to find `~/Code`, etc. I think a find-up search makes a lot of sense as a default. But I would need to be able to walk up and find the first directory that does _not_ contain a `package.json`. So, like [pkg-up](https://github.com/sindresorhus/pkg-up), except not. I suppose ideally it would also keep going if the `basename` is `node_modules`, but I can punt on that. Any thoughts / existing APIs for doing something like this? Probably a new module, but `find-up` is the most relevant thing I am aware of.

**Comment by sindresorhus** [comment]
Nothing I'm aware of. Could maybe add some kind of flexible `matcher` option here that accepts a function to decide whether to match or not, or something. Happy to consider suggestions.

**Comment by sholladay** [comment]
After some experiments, I ended up making [find-down](https://github.com/sholladay/find-down) and [pkg-down](https://github.com/sholladay/pkg-down) instead. They search the same space as `find-up` but start at the root directory. By doing this, I am able to guarantee the result is the topmost package.json. And then I can walk up two directories to find the directory that contains all relevant projects.

**Comment by sholladay** [comment]
After some experiments, I ended up making [find-down](https://github.com/sholladay/find-down) and [pkg-down](https://github.com/sholladay/pkg-down) instead. They search the same space as `find-up` but start at the root directory. By doing this, I am able to guarantee the result is the topmost package.json. And then I can walk up two directories to find the directory that contains all relevant projects.

**Comment by sindresorhus** [comment]
👍
