### ISSUE TITLE
Can't import with Node v16.13.1 Typescript 3.9

### ISSUE THREAD

**Issue by babeal** [sindresorhus/find-up#61]
I've tried multiple forms of importing the module but it keep failing with this error:

Error [ERR_REQUIRE_ESM]: require() of ES Module /.../find-up/index.js from ".../pipeline.ts" is not supported.  Instead change the require of index.js ... to a dynamic import() which is available in all CommonJS modules.  

import return a promise which makes it really difficult to use in a simple script scenario.  

Module may need to be modernized

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by evil-shrike** [comment]
What is the latest published version of find-up that can be used as commonjs module?

Also it'd be nice to see a warning in README that the lib supports only ESM imports.

**Comment by sholladay** [comment]
> What is the latest published version of find-up that can be used as commonjs module?

@evil-shrike it should be v5.0.0. I still feel good recommending that version, it merely lacks a couple of minor convenience features.
