### ISSUE TITLE
Support CJS

### ISSUE THREAD

**Issue by Spades-S** [sindresorhus/find-up#62]
Maybe we can support CJS, because in some case, we need to deal with module interop

``` shell
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/.pnpm/find-up@6.3.0/node_modules/find-up/index.js  not supported.
```

**Comment by sindresorhus** [comment]
I don't have any plans to support CommonJS.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
