### ISSUE TITLE
Request of removing pathExists and pathExistsSync functions

### ISSUE THREAD

**Issue by prisis** [sindresorhus/find-up#66]
This functions are depending on the path-exists package

[pathExists(path)](https://github.com/sindresorhus/find-up#pathexistspath)
Returns a Promise<boolean> of whether the path exists.

[pathExistsSync(path)](https://github.com/sindresorhus/find-up#pathexistssyncpath)
Returns a boolean of whether the path ex

This adds one package that could be replaced totaly with the internal node functions so copy what is done in the package itself
or just remove it and add a documentation, who to use the node functions

What do you think?

**Comment by sindresorhus** [comment]
I don't plan to remove them. But I have made a simpler version of this package: https://github.com/sindresorhus/find-up-simple
