### ISSUE TITLE
7.0.0 breaks when using a bundler (Rollup).

### ISSUE THREAD

**Issue by Jason3S** [sindresorhus/find-up#67]
<img width="586" alt="image" src="https://github.com/sindresorhus/find-up/assets/3740137/2d52de0e-d7ca-425a-a1f7-463071aff39f">

`unicorn-magic/package.json`
```json
	"type": "module",
	"exports": {
		"types": "./index.d.ts",
		"node": "./node.js",
		"default": "./default.js"
	},
```

Rollup is resolving to `default.js` instead of `node.js`. Based upon the default rules used by https://www.npmjs.com/package/@rollup/plugin-node-resolve

See:

https://github.com/sindresorhus/find-up/commit/187b2a14df987a9046b074836932594549238d56#r133637011

Is it really necessary to have a dependency upon `unicore-magic` for a single line function?

**Comment by sindresorhus** [comment]
This is a problem with Rollup, not this package. The `unicorn-magic` package simply uses the `exports` field like it was meant. You need to open an issue on Rollup instead.

**Comment by jrmyio** [comment]
I actually started getting issues since [8.0.0](https://github.com/sindresorhus/find-up/releases/tag/v8.0.0)

```
Error: Cannot parse config file: '........': Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ......./node_modules/.pnpm/find-up@8.0.0/node_modules/unicorn-magic/package.json
```

is this related?
